/*createData('Draft RRs for the recruitment to the posts of Scientist ‘F and Scientist ‘G’ in the Central Soil & Materials Research Station, New Delhi, under the Ministry of Water Resources, RD & GR : Stake holders can mail their comments to etwo-mowr[at]nic[dot]in', 'http://mowr.gov.in/sites/default/files/RR_CWPRS_SC-F-G_Draft_Feb2019.pdf', 25),
createData('Draft RRs for the recruitment to the posts of Scientist ‘F and Scientist ‘G’ in the Central Water and Power Research Station, Pune, under the Ministry of Water Resources, RD & GR : Stake holders can mail their comments to etwo-mowr[at]nic[dot]in', 452, 25.0),
createData('Jal Charcha Monthly Magazine of Ministry of Water Resources, RD & GR', 262, 16.0),
createData('Amendment of Recruitment Regulations (RRs) for the Group \'B\' Posts in Brahmaputra Board - Comments on revised draft RRs', 159, 6.0),
createData('Guidelines to regulate and control Ground Water Extraction in India', 356, 16.0),
createData('Year End Review - 2018: Ministry of Water Resources, River Development and Ganga Rejuvenation', 408, 3.2),
createData('Amendment of Recruitment Rules for the Non-Statutory Group \'A\' Posts in Brahmaputra Board - comments of stakeholders invited on revised draft', 237, 9.0),
createData('Hydro-Meteorological Data Dissemination Policy, 2018', 375, 0.0),
createData('Operational Guidelines for Pradhan MantriKrishiSinchaiYojana(PMKSY) HarKhetKoPani (HKKP) - Ground Water Irrigation', 518, 26.0),
createData('1st International Conference on “Sustainable Water Management” (10-11 December 2018, Chandigarh, India), organized by Bhakra Beas Management Board (BBMB) under the aegis of National Hydrology Project (NHP), Ministry of Water Resources, River Development ', 392, 0.2),
createData('Marshmallow', 318, 0),
createData('Nougat', 360, 19.0),
createData('Oreo', 437, 18.0),*/